version: '3.6'
services:

  server:
    command: npm run start:dev
    build: .
    volumes:
      - ./:/home/node # same folder structure on local machine and docker container
    working_dir: /home/node
    ports:
      - "3001:3001" # open port for server api
      - "9222:9222" # open port for inspector to debug
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: elasticsearch
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
volumes:
  esdata:
    driver: local